language: ruby
services:
  - docker
branches:
  only:
  - master
after_success:
 - docker run --rm --label=jekyll --volume="$(pwd)":/srv/jekyll -e JEKYLL_ENV='production' jekyll/jekyll:3.7.0 jekyll build 
 - cd _site
 - git init .
 - git config --global user.email "travis@travis-ci.org"
 - git config --global user.name "Travis"
 - git remote add origin https://${GH_TOKEN}@github.com/Jumia/techinporto.git
 - git checkout -b gh-page
 - git add --all -f .
 - git commit -a -m "Travis - ${TRAVIS_BUILD_NUMBER}"
 - git push --force origin gh-page
