# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TECHINPORTO
email: info@techinporto.com
description: > # this means to ignore newlines until "baseurl:"
  TECHINPORTO - 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.techinporto.com" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: PortoTechCenter
#github_username:  jumiaGroup
#facebook_username: JumiaPortoTechCenter

social:
  - title: twitter
    url: https://twitter.com/techinporto
  - title: facebook
    url: https://www.facebook.com/techinporto/

google_analytics: UA-97006991-1

google_maps_key: AIzaSyD3OBDdCNU7pVw5u_KtOSWFP6jK901UhEc

# Build settings
sass:
    style: compressed
markdown: kramdown
theme: minima

collections:
  speakers:
    output: true
    permalink: /speakers/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - POST_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md
